[package]
name = "myopic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gomokugen = { git = "https://github.com/cosmobobak/gomokugen.git", version = "0.1.0" }
kn-graph = "0.5.0"
